### PR TITLE
Fix Disparate signatures of Post-extending classes

### LINKED ISSUE #40: Fatal Error: incompatible extended methods
On Chassis with PHP7.2, I get the following fatal error when attempting to load WP:

It looks like the signatures of each of the extended types are different and we can no longer get away with this.

`Fatal error: Declaration of HMCI\Inserter\WP\Attachment::insert($path, $post_data = Array, $canonical_id = false, $post_meta = Array, $file_type_override = NULL, $force_update_existing = true) must be compatible with HMCI\Inserter\WP\Post::insert($post_data = Array, $canonical_id = false, $post_meta = Array) in /vagrant/content/client-mu-plugins/hm-content-import/inc/classes/inserter/wp/attachment.php on line 0`

|  | Time | Memory | Function | Location |
| ------------- | ------------- | ------------- | ------------- | ------------- |
| 1 | 0.0004 | 396696 | {main}( ) | .../index.php:0 |
| 2 | 0.0018 | 396984 | require( '/vagrant/wp/wp-blog-header.php' ) | .../index.php:7 |
| 3 | 0.0025 | 397336 | require_once( '/vagrant/wp/wp-load.php' ) | .../wp-blog-header.php:13 |
| 4 | 0.0040 | 398256 | require_once( '/vagrant/wp-config.php' ) | .../wp-load.php:42 |
| 5 | 0.0089 | 402200 | require_once( '/vagrant/wp/wp-settings.php' ) | .../wp-config.php:145 |
| 6 | 0.1682 | 3297088 | include_once( '/vagrant/content/mu-plugins/z-client-mu-plugins.php' ) | .../wp-settings.php:260 |
| 7 | 0.1727 | 3299176 | include_once( '/vagrant/content/client-mu-plugins/loader.php' ) | .../z-client-mu-plugins.php:117 |
| 8 | 0.1779 | 3300576 | require_once( '/vagrant/content/client-mu-plugins/hm-content-import/hm-content-import.php' ) | .../loader.php:26 |

Additionally: 
`Fatal error: Declaration of HMCI\Inserter\WP\Guest_Author::insert($user_data = Array, $canonical_id = false, $author_meta = Array) must be compatible with HMCI\Inserter\WP\Post::insert($post_data = Array, $canonical_id = false, $post_meta = Array, $options = Array) in /vagrant/content/client-mu-plugins/hm-content-import/inc/classes/inserter/wp/guest-author.php on line 0`
`Fatal error: Declaration of HMCI\Inserter\WP\Attachment::exists($canonical_id) must be compatible with HMCI\Inserter\WP\Post::exists($canonical_id, $post_type = 'post') in /vagrant/content/client-mu-plugins/hm-content-import/inc/classes/inserter/wp/attachment.php on line 0`

### PR DESCRIPTION
**Pull request by mikeselander**
The signatures for several methods on classes extending `HMCI\Inserter\WP\Post` had different signatures which will no longer fly in newer PHP versions. 

This attempts to make the signatures more consistent and reduce some unnecessary redundancies.

Resolves #40

### CODE REVIEW

File: inc/classes/inserter/wp/attachment.php [hunk 1]
```diff
@@ -13,42 +13,40 @@ class Attachment extends Post {
...
+	 *
+	 * @param array $post_data    Post data formatted as it will be saved to the posts table. Should match WP_Post data.
+	 * @param bool  $canonical_id Use an existing canonical ID.
+	 * @param array $post_meta    Metadata to assign to the post.
+	 * @param array $options      Additional data about the post.
 	 * @return array|int|object|\WP_Error
 	 */
-	static function insert( $path, $post_data = array(), $canonical_id = false, $post_meta = array(), $file_type_override = null, $force_update_existing = true ) {
-
+	static function insert( $post_data = [], $canonical_id = false, $post_meta = [], $options = [] ) {
```
Comment (tcrsavage) [inline inc/classes/inserter/wp/attachment.php]: It majorly sucks that the most prominent arg has to be defined as an element of an array in the last function arg.

Probably best way around this for now would be

```
function insert_from_path( $path, $post_data = [], $canonical_id = false, $post_meta = [], $options = []  ) {
    return static::insert( $post_data ...
}
```

```
function insert_from_url( $url, $post_data = [], $canonical_id = false, $post_meta = [], $options = []  ) {
    return static::insert( $post_data ...
}
```

File: inc/classes/inserter/wp/attachment.php [hunk 2]
```diff
@@ -13,42 +13,40 @@ class Attachment extends Post {
...
-	 * @param array $post_data
-	 * @param bool $canonical_id
-	 * @param array $post_meta
-	 * @param null $file_type_override
-	 * @param bool $force_update_existing
+	 *
+	 * @param array $post_data    Post data formatted as it will be saved to the posts table. Should match WP_Post data.
+	 * @param bool  $canonical_id Use an existing canonical ID.
+	 * @param array $post_meta    Metadata to assign to the post.
+	 * @param array $options      Additional data about the post.
```
Comment (tcrsavage) [inline inc/classes/inserter/wp/attachment.php]: Will want to list all available args

```
@param array $options      Additional data about the post.
 Args 
  - string path The local dir path or remote url of the file
...
```

**Comment by tcrsavage** [comment]
Am ok with merging this straight into master, but will also want the changes merged into develop.

@shadyvb you will also want to be aware of these changes I guess

**Comment by tcrsavage** [comment]
@mikeselander I don't think we need the develop branch really moving forward, happy for this to go into master.

**Comment by mikeselander** [comment]
Alright, mind one more last look @tcrsavage?

**Comment by mikeselander** [comment]
I've restored those methods with the post type defaulted in both attachment and guest-author. It would probably be better to have some awareness throughout the whole class of the current post type with a variable instead, but kept to current patterns for now to reduce churn.

**Comment by mikeselander** [comment]
This is becoming a blocker for SS so I'm going to merge it now. Happy to fix any knock-ons or other adjustments here.
